In [47]:
# q1 and 5
import numpy as np

arr = np.array([[1,2,3],[4,5,6]]);
print(arr)
array = arr.astype(np.float32)
print(array)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [44]:
#q4
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
numarr = 5*np.ones((5,4))
print(numarr)
# print(np.linalg.det(numarr))
print(np.sum(numarr,axis=1))
after = numarr.reshape(10,2)
print(after)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[20. 20. 20. 20. 20.]
[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]


In [26]:
zeroes = np.zeros((3,5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
ide = np.identity(5)
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
# q6
a = np.array([[0,0,1,0,0],[1,0,0,1,0], [1,0,1,0,0]])
a.astype(np.bool_)

array([[False, False,  True, False, False],
       [ True, False, False,  True, False],
       [ True, False,  True, False, False]])

In [45]:
arr1 = 5*np.ones((5,5))
print(arr1)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [40]:
arr2 = np.random.randint(40, size=12)
print(arr2)


[14 13  6  0 24  8  8 24 39 33 15 14]


In [42]:
arr3 = 5*np.identity(10)
print(arr3)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [ ]:
# 18


In [56]:
# @19
from numpy.linalg import norm
A = np.array([[2,1,2],[3,2,9], [-1,2,-3]])
B = np.array([3,4,2])
print(A)
print(B)
cosine = np.dot(A,B)/(norm(A, axis=1)*norm(B))
print(cosine)


[[ 2  1  2]
 [ 3  2  9]
 [-1  2 -3]]
[3 4 2]
[ 0.86657824  0.67035541 -0.04962917]


In [57]:
# 20

array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)
indices = np.argsort(array)
print(indices)

[ 10  52  62  16  16  54 453]
[0 3 4 1 5 2 6]
